[profile.default]
src = 'contracts'
libs = ['node_modules']
out = 'forge-out'

optimizer_runs = 5000
solc_version = '0.8.17'

# See more config options https://github.com/gakonst/foundry/tree/master/config
block_base_fee_per_gas = 100000000 
block_number = 120000 
block_timestamp = 1640000000 
evm_version = 'shanghai' 
fs_permissions = [{access = "read-write", path = "./"}] 
gas_limit = 9223372036854775807 # the gas limit in tests

[fuzz]
max_test_rejects = 1000000
runs = 256
